
defaults:
  env:
    id: ColourBombGridWorldV2
    max_episode_steps: 250
    label_fn: masa.envs.tabular.colour_bomb_grid_world_v2:label_fn
    cost_fn: masa.envs.tabular.colour_bomb_grid_world_v2:cost_fn
  
  constraint:
    type: CMDP
    cost_budget: 0

  run:
    total_timesteps: 500000
    eval_every: 10000
    eval_episodes: 10
    log_every: 10000
    stats_window_size: 100

Property2:
  constraint:
    type: LTL_SAFETY
    dfa: masa.examples.colour_bomb_grid_world.property_2:make_dfa

Property3:
  constraint:
    type: LTL_SAFETY
    dfa: masa.examples.colour_bomb_grid_world.property_3:make_dfa