defaults:
  env:
    id: MediaStreamingV2
    max_episode_steps: 100
    label_fn: masa.envs.tabular.media_streaming_v2:label_fn
    cost_fn: masa.envs.tabular.media_streaming_v2:cost_fn

  constraint:
    type: PCTL
    alpha: 0.01

  run:
    total_timesteps: 1000000
    eval_every: 10000
    eval_episodes: 10
    log_every: 10000
    stats_window_size: 100