defaults:  
  env:
    id: Road1D
    max_episode_steps: 200
    label_fn: masa.envs.continuous.road_1d:label_fn
    cost_fn: masa.envs.continuous.road_1d:cost_fn

  constraint:
    type: CMDP
    cost_budget: 0

  run:
    total_timesteps: 50000
    eval_every: 2500
    eval_episodes: 1
    log_every: 2500
    stats_window_size: 10