defaults:
  env:
    id: sokoban
    max_episode_steps: 300
    label_fn: masa.envs.discrete.sokoban:label_fn
    cost_fn: masa.envs.discrete.sokoban:cost_fn

  constraint:
    type: cmdp
    cost_budget: 0

  run:
    total_timesteps: 100000
    eval_every: 5000
    eval_episodes: 10
    log_every: 5000
    stats_window_size: 100