defaults:
  learning_rate: 1e-3
  n_steps: 2048
  n_critic_updates: 10
  gamma: 0.99
  gae_lambda: 0.95
  normalize_reward_advantages: True
  normalize_cost_advantages: True
  ent_coef: 0.0
  vf_coef: 1.0
  max_grad_norm: 0.5
  target_kl: 0.01
  cg_iters: 15
  cg_damping: 0.1
  fvp_sample_freq: 1
  line_search_steps: 15
  line_search_decay: 0.8
  policy_kwargs: {net_arch: [64, 64], log_std_init: 0.0}
  cost_limit: 25.0
  cost_gamma: 0.99
  cost_gae_lambda: 0.95