defaults:
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  normalize_advantage: True
  ent_coef: 0.0
  vf_coef: 1.0
  max_grad_norm: 0.5
  policy_kwargs: {net_arch: [64, 64], log_std_init: 0.0}