defaults:
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  normalize_reward_advantages: True
  normalize_cost_advantages: True
  ent_coef: 0.0
  vf_coef: 1.0
  max_grad_norm: 0.5
  policy_kwargs: {net_arch: [64, 64], log_std_init: 0.0}
  cost_limit: 25.0
  cost_gamma: 0.99
  cost_gae_lambda: 0.95
  lagrangian_multiplier_init: 0.0
  lambda_lr: 0.01
  lagrangian_upper_bound: 100.0

MediaStreaming:
  gamma: 0.95
  cost_limit: 0.04
  cost_gamma: 0.95
  lagrangian_multiplier_init: 100.0

BridgeCrossing:
  gamma: 0.99
  cost_limit: 0.05
  cost_gamma: 0.95
  lagrangian_multiplier_init: 10.0

BridgeCrossingV2:
  gamma: 0.99
  cost_limit: 0.01
  cost_gamma: 0.95
  lagrangian_multiplier_init: 10.0

ColourBombGridWorld:
  gamma: 0.95
  cost_limit: 0.05
  cost_gamma: 0.99
  lagrangian_multiplier_init: 10.0

ColourBombGridWorld_Property2:
  gamma: 0.95
  cost_limit: 0.05
  cost_gamma: 0.99
  lagrangian_multiplier_init: 10.0

ColourBombGridWorldV2:
  gamma: 0.95
  cost_limit: 0.025
  cost_gamma: 0.99
  lagrangian_multiplier_init: 10.0

ColourBombGridWorldV2_Property2:
  gamma: 0.95
  cost_limit: 0.025
  cost_gamma: 0.99
  lagrangian_multiplier_init: 10.0

ColourBombGridWorldV2_Property3:
  gamma: 0.95
  cost_limit: 0.025
  cost_gamma: 0.99
  lagrangian_multiplier_init: 10.0

MiniPacman:
  gamma: 0.95
  cost_limit: 0.01
  cost_gamma: 0.9
  lagrangian_multiplier_init: 10.0