defaults:
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  normalize_advantage: True
  ent_coef: 0.0
  vf_coef: 1.0
  max_grad_norm: 0.5
  policy_kwargs: {net_arch: [64, 64], log_std_init: -1.0, conditional_beta_network: True}
  init_safety_bound: 0.01
  theta: 1e-15
  max_vi_steps: 10000

MediaStreaming:
  gamma: 0.95
  init_safety_bound: 0.04

BridgeCrossing:
  gamma: 0.99
  init_safety_bound: 0.05

BridgeCrossingV2:
  gamma: 0.99
  init_safety_bound: 0.01

ColourBombGridWorld:
  gamma: 0.95
  init_safety_bound: 0.05

ColourBombGridWorld_Property2:
  gamma: 0.95
  init_safety_bound: 0.05

ColourBombGridWorldV2:
  gamma: 0.95
  init_safety_bound: 0.025

ColourBombGridWorldV2_Property2:
  gamma: 0.95
  init_safety_bound: 0.025
  policy_kwargs: {log_std_init: -2.0}

ColourBombGridWorldV2_Property3:
  gamma: 0.95
  init_safety_bound: 0.025
  policy_kwargs: {log_std_init: -2.0}

MiniPacman:
  gamma: 0.95
  init_safety_bound: 0.01
  policy_kwargs: {log_std_init: 0.0}