defaults:
  alpha: 0.1
  cost_lambda: 1.0
  gamma: 0.9
  exploration: boltzmann
  boltzmann_temp: 0.05
  initial_epsilon: 1.0
  final_epsilon: 0.1
  epsilon_decay: linear
  epsilon_decay_frames: 10000