defaults:
  task_alpha: 0.1
  task_gamma: 0.95
  safe_alpha: 0.1
  safe_gamma: 0.95
  model_free_alpha: 0.1
  mode: model_free
  model_checking: exact
  samples: 8192
  horizon: 5
  safety_prob: 0.01
  r_min: 0.0
  cost_coef: 10.0
  exploration: boltzmann
  boltzmann_temp: 0.05
  initial_epsilon: 1.0
  final_epsilon: 0.1
  epsilon_decay: linear
  epsilon_decay_frames: 10000

MediaStreaming:
  task_alpha: 0.1
  task_gamma: 0.95
  safe_alpha: 0.1
  safe_gamma: 0.95
  model_free_alpha: 0.1
  mode: model_free
  horizon: 5
  safety_prob: 0.04
  cost_coef: 100.0
  r_min: -1.0

BridgeCrossing:
  task_alpha: 0.05
  task_gamma: 0.99
  safe_alpha: 0.05
  safe_gamma: 0.95
  model_free_alpha: 0.05
  mode: model_free
  horizon: 4
  safety_prob: 0.05
  cost_coef: 10.0

BridgeCrossingV2:
  task_alpha: 0.1
  task_gamma: 0.99
  safe_alpha: 0.1
  safe_gamma: 0.95
  model_free_alpha: 0.1
  mode: model_free
  horizon: 4
  safety_prob: 0.01
  cost_coef: 10.0

ColourBombGridWorld:
  task_alpha: 0.05
  task_gamma: 0.95
  safe_alpha: 0.05
  safe_gamma: 0.95
  model_free_alpha: 0.05
  mode: model_free
  horizon: 2
  safety_prob: 0.05
  cost_coef: 10.0

ColourBombGridWorld_Property2:
  task_alpha: 0.05
  task_gamma: 0.95
  safe_alpha: 0.05
  safe_gamma: 0.95
  model_free_alpha: 0.05
  mode: model_free
  horizon: 2
  safety_prob: 0.05
  cost_coef: 10.0

ColourBombGridWorldV2:
  task_alpha: 0.05
  task_gamma: 0.95
  safe_alpha: 0.05
  safe_gamma: 0.95
  model_free_alpha: 0.05
  mode: model_free
  horizon: 9
  safety_prob: 0.025
  cost_coef: 10.0

ColourBombGridWorldV2_Property2:
  task_alpha: 0.05
  task_gamma: 0.95
  safe_alpha: 0.05
  safe_gamma: 0.95
  model_free_alpha: 0.05
  mode: model_free
  horizon: 9
  safety_prob: 0.025
  cost_coef: 10.0

ColourBombGridWorldV2_Property3:
  task_alpha: 0.05
  task_gamma: 0.95
  safe_alpha: 0.05
  safe_gamma: 0.99
  model_free_alpha: 0.05
  mode: model_free
  horizon: 9
  safety_prob: 0.025
  cost_coef: 10.0

MiniPacman:
  task_alpha: 0.1
  task_gamma: 0.95
  safe_alpha: 0.1
  safe_gamma: 0.95
  model_free_alpha: 0.1
  mode: model_free
  horizon: 9
  safety_prob: 0.01
  cost_coef: 10.0
  
